### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by musician2000** [eschizoid/urban-alexa#3]
Hi Does this code still work? followed your instructions but when testing I get The remote endpoint could not be called, or the response it returned was invalid.

**Comment by khtims75** [comment]
I am experiencing the same issue. Please let me know what I've done wrong.

**Comment by khtims75** [comment]
I found a solution that worked for me and could possibly work for you too. unzip the urban-alexa-0.0.1.zip file (you probably did this to put your appId in the code.) Instead of replacing it in the index.js file I put the appId in the config.json file where it's being called from. That same file has the endpoint in it. I changed mine to http://api.urbandictionary.com/v0/define?term= instead of http://api.urbandictionary.com/v0/define. Then save changes. Now you need to zip it back up so don't zip the outer folder. Zip the contents of the folder (7 items I believe). When I did this on my mac it created an Archive.zip file. When I uploaded that file to Lamda then it started working. The test on AWS worked and so did my voice commands. Hope that helps.

**Comment by eschizoid** [comment]
@musician2000 Sorry for my late reply, yes this code still should work. Let me know if you are still experiencing any issue.

**Comment by musician2000** [comment]
Hi Thanks, I worked it out with Khtims75 comments and changes mentioned. All working now, Thank you!
